apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stackit-cl-d3fx0oqd-app-of-apps
spec:
  project: default
  source:
    repoURL: https://github.com/mahauber/argocd-app-of-apps-test
    targetRevision: HEAD
    path: charts/general
    helm:
      valueFiles:
        - ../../cluster/cl-d3fx0oqd/values.yaml
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
